/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistas.sistema;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.mycompany.controladores.DecanoControlador;
import com.mycompany.idecanos.*;
import com.mycompany.vistas.MainWindow;
import com.mycompany.vistas.paneles.DecanosPanel;

/**
 *
 * @author ibarr
 */
public class DecanoVista extends javax.swing.JFrame {

    /**
     * Creates new form DecanosVista
     */
    private DecanoControlador decanoControlador;
    private MainWindow vistaDecano;
    // VARIABLES PARA MANEJAR EL MODO DE ACTUALIZACIÓN
    private boolean modoActualizacion = false;
    private int idDecanoActualizar = -1;
    private int filaTabla = -1;
    private DecanosPanel panelDecanos;

    public DecanoVista() {
        initComponents();
        decanoControlador = new DecanoControlador(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public DecanoVista(MainWindow vistaDecano) {
        initComponents();
        decanoControlador = new DecanoControlador(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.vistaDecano = vistaDecano;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoJPanel = new javax.swing.JPanel();
        toorbarJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contenidoJPanel = new javax.swing.JPanel();
        ingreseLosSiguientesDatosJLabel = new javax.swing.JLabel();
        NombreJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        cedulaJLabel = new javax.swing.JLabel();
        correoInstitucionalJLabel = new javax.swing.JLabel();
        correoPersonalJLabel = new javax.swing.JLabel();
        sueldoJLabel = new javax.swing.JLabel();
        dedicacionJLabel = new javax.swing.JLabel();
        nivelJLabel = new javax.swing.JLabel();
        entradaNombreJTextField = new javax.swing.JTextField();
        entradaIdJTextField = new javax.swing.JTextField();
        entradaCedulaJTextField = new javax.swing.JTextField();
        entradaCorreoInstitucionalJTextField = new javax.swing.JTextField();
        entradaCorreoPersonalJTextField = new javax.swing.JTextField();
        entradaSueldoJTextField = new javax.swing.JTextField();
        entradaDedicacionJTextField = new javax.swing.JTextField();
        entradaNivelJTextField = new javax.swing.JTextField();
        btnAgregarDecanoJButton = new javax.swing.JButton();
        btnCancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toorbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DECANOS");

        javax.swing.GroupLayout toorbarJPanelLayout = new javax.swing.GroupLayout(toorbarJPanel);
        toorbarJPanel.setLayout(toorbarJPanelLayout);
        toorbarJPanelLayout.setHorizontalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toorbarJPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toorbarJPanelLayout.setVerticalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toorbarJPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        fondoJPanel.add(toorbarJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        contenidoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        ingreseLosSiguientesDatosJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ingreseLosSiguientesDatosJLabel.setText("INGRESE LOS SIGUIENTES DATOS");

        NombreJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreJLabel.setText("Nombre");

        idJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idJLabel.setText("ID");

        cedulaJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cedulaJLabel.setText("Cedula");

        correoInstitucionalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoInstitucionalJLabel.setText("Correo Institucional");

        correoPersonalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoPersonalJLabel.setText("Correo Personal");

        sueldoJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        sueldoJLabel.setText("Sueldo");

        dedicacionJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        dedicacionJLabel.setText("Dedicacion");

        nivelJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nivelJLabel.setText("Nivel");

        btnAgregarDecanoJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnAgregarDecanoJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarDecanoJButton.setText("Agregar");
        btnAgregarDecanoJButton.setBorder(null);
        btnAgregarDecanoJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarDecanoJButtonMouseClicked(evt);
            }
        });

        btnCancelarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnCancelarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarJButton.setText("Cancelar");
        btnCancelarJButton.setBorder(null);
        btnCancelarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoJPanelLayout = new javax.swing.GroupLayout(contenidoJPanel);
        contenidoJPanel.setLayout(contenidoJPanelLayout);
        contenidoJPanelLayout.setHorizontalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoJPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(NombreJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(idJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(correoInstitucionalJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(entradaCorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(cedulaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(sueldoJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaSueldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(dedicacionJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaDedicacionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(correoPersonalJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(nivelJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entradaNivelJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(btnAgregarDecanoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ingreseLosSiguientesDatosJLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(166, 166, 166))
        );
        contenidoJPanelLayout.setVerticalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ingreseLosSiguientesDatosJLabel)
                .addGap(18, 18, 18)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreJLabel)
                    .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJLabel)
                    .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaJLabel)
                    .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoInstitucionalJLabel)
                    .addComponent(entradaCorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoPersonalJLabel)
                    .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoJLabel)
                    .addComponent(entradaSueldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dedicacionJLabel)
                    .addComponent(entradaDedicacionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nivelJLabel)
                    .addComponent(entradaNivelJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarDecanoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        fondoJPanel.add(contenidoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDecanoJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarDecanoJButtonMouseClicked
        // TODO add your handling code here:
        if (modoActualizacion) {
            // PROCESAR ACTUALIZACIÓN
            Decano[] decanosActualizados = decanoControlador.procesoActualizarDecano();
            if (decanosActualizados != null && panelDecanos != null) {
                panelDecanos.actualizarTabla(decanosActualizados);
            }
        } else {
            // PROCESAR AGREGACIÓN
            Decano[] decanos = decanoControlador.procesoControladorDecano();
            if (decanos != null && vistaDecano != null) {
                vistaDecano.getDecanosPanel().actualizarTabla(decanos);
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnAgregarDecanoJButtonMouseClicked

    private void btnCancelarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarJButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarJButtonMouseClicked


    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "", JOptionPane.ERROR_MESSAGE);
    }

    public String getEntradaNombreJTextField() {
        return entradaNombreJTextField.getText();
    }

    public String getEntradaIdJTextField() {
        return entradaIdJTextField.getText();
    }

    public String getEntradaCedulaJTextField() {
        return entradaCedulaJTextField.getText();
    }

    public String getEntradaCorreoInstitucionalJTextField() {
        return entradaCorreoInstitucionalJTextField.getText();
    }

    public String getEntradaCorreoPersonalJTextField() {
        return entradaCorreoPersonalJTextField.getText();
    }

    public String getEntradaSueldoJTextField() {
        return entradaSueldoJTextField.getText();
    }

    public String getEntradaDedicacionJTextField() {
        return entradaDedicacionJTextField.getText();
    }

    public String getEntradaNivelJTextField() {
        return entradaNivelJTextField.getText();
    }

    // MÉTODO PARA CONFIGURAR EL MODO DE ACTUALIZACIÓN
    public void configurarModoActualizacion(Decano decano, int fila, DecanosPanel panel) {
        this.modoActualizacion = true;
        this.idDecanoActualizar = decano.getId();
        this.filaTabla = fila;
        this.panelDecanos = panel;
        
        // LLENAR LOS CAMPOS CON LOS DATOS DEL DECANO
        entradaNombreJTextField.setText(decano.getNombre());
        entradaIdJTextField.setText(String.valueOf(decano.getId()));
        entradaIdJTextField.setEditable(false); // No permitir cambiar el ID
        entradaCedulaJTextField.setText(decano.getCedula());
        entradaCorreoInstitucionalJTextField.setText(decano.getCorreoInstitucional());
        entradaCorreoPersonalJTextField.setText(decano.getCorreoPersonal());
        entradaSueldoJTextField.setText(String.valueOf(decano.getSueldo()));
        entradaDedicacionJTextField.setText(decano.getDedicacion());
        entradaNivelJTextField.setText(decano.getNivel());
        
        // CAMBIAR EL TEXTO DEL BOTÓN Y EL TÍTULO
        btnAgregarDecanoJButton.setText("Actualizar");
        jLabel1.setText("ACTUALIZAR DECANO");
    }
    
    // MÉTODO PARA VERIFICAR SI ESTÁ EN MODO ACTUALIZACIÓN
    public boolean esModoActualizacion() {
        return modoActualizacion;
    }
    
    // MÉTODO PARA OBTENER EL ID DEL DECANO A ACTUALIZAR
    public int getIdDecanoActualizar() {
        return idDecanoActualizar;
    }


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreJLabel;
    private javax.swing.JButton btnAgregarDecanoJButton;
    private javax.swing.JButton btnCancelarJButton;
    private javax.swing.JLabel cedulaJLabel;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JLabel correoInstitucionalJLabel;
    private javax.swing.JLabel correoPersonalJLabel;
    private javax.swing.JLabel dedicacionJLabel;
    private javax.swing.JTextField entradaCedulaJTextField;
    private javax.swing.JTextField entradaCorreoInstitucionalJTextField;
    private javax.swing.JTextField entradaCorreoPersonalJTextField;
    private javax.swing.JTextField entradaDedicacionJTextField;
    private javax.swing.JTextField entradaIdJTextField;
    private javax.swing.JTextField entradaNivelJTextField;
    private javax.swing.JTextField entradaNombreJTextField;
    private javax.swing.JTextField entradaSueldoJTextField;
    private javax.swing.JPanel fondoJPanel;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel ingreseLosSiguientesDatosJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nivelJLabel;
    private javax.swing.JLabel sueldoJLabel;
    private javax.swing.JPanel toorbarJPanel;
    // End of variables declaration//GEN-END:variables
}