
package com.mycompany.vistas.sistema;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.mycompany.controladores.EstudianteControlador;
import com.mycompany.iestudiantes.IEstudiantes;
public class EstudianteVista extends javax.swing.JFrame {

    /**
     * Creates new form EstudiantesVista
     */
    private EstudianteControlador estudiantesControlador;

    public EstudianteVista() {
        initComponents();
        estudiantesControlador = new EstudianteControlador(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoJPanel2 = new javax.swing.JPanel();
        contenidoJPanel = new javax.swing.JPanel();
        ingreseSiguientesDatosJLabel = new javax.swing.JLabel();
        CedulaJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        correoInstitucionalJLabel = new javax.swing.JLabel();
        correoPersonalJLabel = new javax.swing.JLabel();
        codigoJLabel = new javax.swing.JLabel();
        entradaIdJTextField = new javax.swing.JTextField();
        entradaCorreoPersonalJTextField = new javax.swing.JTextField();
        entradaNombreJTextField = new javax.swing.JTextField();
        entradacorreoInstitucionalJTextField = new javax.swing.JTextField();
        nombreJLabel = new javax.swing.JLabel();
        entradaCedulaJTextField = new javax.swing.JTextField();
        entradaCodigoJTextField = new javax.swing.JTextField();
        btnCancelarJButton = new javax.swing.JButton();
        btnAgregarJButton = new javax.swing.JButton();
        toorbarJPanel = new javax.swing.JPanel();
        estudiantesJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenidoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        ingreseSiguientesDatosJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ingreseSiguientesDatosJLabel.setText("INGRESE LOS SIGUIENTES DATOS");

        CedulaJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CedulaJLabel.setText("Cedula");

        idJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idJLabel.setText("ID");

        correoInstitucionalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoInstitucionalJLabel.setText("Correo Institucional");

        correoPersonalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoPersonalJLabel.setText("Correo Personal");

        codigoJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        codigoJLabel.setText("Código");

        nombreJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombreJLabel.setText("Nombre");

        btnCancelarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnCancelarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarJButton.setText("Cancelar");
        btnCancelarJButton.setBorder(null);
        btnCancelarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarJButtonMouseClicked(evt);
            }
        });

        btnAgregarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnAgregarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarJButton.setText("Agregar");
        btnAgregarJButton.setBorder(null);
        btnAgregarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoJPanelLayout = new javax.swing.GroupLayout(contenidoJPanel);
        contenidoJPanel.setLayout(contenidoJPanelLayout);
        contenidoJPanelLayout.setHorizontalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idJLabel)
                            .addComponent(correoInstitucionalJLabel)
                            .addComponent(codigoJLabel)
                            .addComponent(CedulaJLabel)
                            .addComponent(nombreJLabel)
                            .addComponent(correoPersonalJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaIdJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradacorreoInstitucionalJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCodigoJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(169, 169, 169))
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(btnAgregarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ingreseSiguientesDatosJLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        contenidoJPanelLayout.setVerticalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ingreseSiguientesDatosJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nombreJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idJLabel))))
                .addGap(18, 18, 18)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CedulaJLabel)
                    .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoInstitucionalJLabel)
                    .addComponent(entradacorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoPersonalJLabel)
                    .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoJLabel)
                    .addComponent(entradaCodigoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        toorbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        estudiantesJLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        estudiantesJLabel.setForeground(new java.awt.Color(255, 255, 255));
        estudiantesJLabel.setText("ESTUDIANTES");

        javax.swing.GroupLayout toorbarJPanelLayout = new javax.swing.GroupLayout(toorbarJPanel);
        toorbarJPanel.setLayout(toorbarJPanelLayout);
        toorbarJPanelLayout.setHorizontalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toorbarJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(estudiantesJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toorbarJPanelLayout.setVerticalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toorbarJPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(estudiantesJLabel)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout fondoJPanel2Layout = new javax.swing.GroupLayout(fondoJPanel2);
        fondoJPanel2.setLayout(fondoJPanel2Layout);
        fondoJPanel2Layout.setHorizontalGroup(
            fondoJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenidoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toorbarJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoJPanel2Layout.setVerticalGroup(
            fondoJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoJPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(toorbarJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarJButtonMouseClicked
        // TODO add your handling code here:
        estudiantesControlador.procesoControladorEstudiante();
        
    }//GEN-LAST:event_btnAgregarJButtonMouseClicked

    private void btnCancelarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarJButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    

    public String getEntradaNombreJTextField() {
        return entradaNombreJTextField.getText();
    }

    public String getEntradaIdJTextField() {
        return entradaIdJTextField.getText();
    }

    public String getEntradaCedulaJTextField() {
        return entradaCedulaJTextField.getText();
    }

    public String getEntradaCorreoInstitucionalJTextField() {
        return entradacorreoInstitucionalJTextField.getText();
    }

    public String getEntradaCorreoPersonalJTextField() {
        return entradaCorreoPersonalJTextField.getText();
    }

    public String getEntradaCodigoJTextField() {
        return entradaCodigoJTextField.getText();
    }

    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CedulaJLabel;
    private javax.swing.JButton btnAgregarJButton;
    private javax.swing.JButton btnCancelarJButton;
    private javax.swing.JLabel codigoJLabel;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JLabel correoInstitucionalJLabel;
    private javax.swing.JLabel correoPersonalJLabel;
    private javax.swing.JTextField entradaCedulaJTextField;
    private javax.swing.JTextField entradaCodigoJTextField;
    private javax.swing.JTextField entradaCorreoPersonalJTextField;
    private javax.swing.JTextField entradaIdJTextField;
    private javax.swing.JTextField entradaNombreJTextField;
    private javax.swing.JTextField entradacorreoInstitucionalJTextField;
    private javax.swing.JLabel estudiantesJLabel;
    private javax.swing.JPanel fondoJPanel2;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel ingreseSiguientesDatosJLabel;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JPanel toorbarJPanel;
    // End of variables declaration//GEN-END:variables
}
