
package com.mycompany.vistas.sistema;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


import com.mycompany.controladores.*;
import com.mycompany.ipersonasexternas.PersonaExterna;
import com.mycompany.vistas.MainWindow;
public class PersonaExternaVista extends javax.swing.JFrame {

    /**
     * Creates new form PersonaExternaVista
     */
    private PersonaExternaControlador personaExternaControlador;
    private MainWindow vistaPersonaExterna;
    public PersonaExternaVista(MainWindow vistaPersonaExterna) {
        initComponents();
        personaExternaControlador = new PersonaExternaControlador(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.vistaPersonaExterna = vistaPersonaExterna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoJPanel = new javax.swing.JPanel();
        toorbarJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contenidoJPanel = new javax.swing.JPanel();
        ingreseSiguientesDatosJLabel = new javax.swing.JLabel();
        nombreJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        cedulaJLabel = new javax.swing.JLabel();
        correoPersonalJLabel = new javax.swing.JLabel();
        descripcionJLabel = new javax.swing.JLabel();
        entradaNombreJTextField = new javax.swing.JTextField();
        entradaIdJTextField = new javax.swing.JTextField();
        entradaCedulaJTextField = new javax.swing.JTextField();
        entradaCorreoPersonalJTextField = new javax.swing.JTextField();
        entadaDescripcionJTextField = new javax.swing.JTextField();
        btnAgregarJButton = new javax.swing.JButton();
        btnCancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toorbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERSONA EXTERNA");

        javax.swing.GroupLayout toorbarJPanelLayout = new javax.swing.GroupLayout(toorbarJPanel);
        toorbarJPanel.setLayout(toorbarJPanelLayout);
        toorbarJPanelLayout.setHorizontalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toorbarJPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        toorbarJPanelLayout.setVerticalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toorbarJPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        fondoJPanel.add(toorbarJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contenidoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        ingreseSiguientesDatosJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ingreseSiguientesDatosJLabel.setText("INGRESE LOS SIGUIENTES DATOS");

        nombreJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombreJLabel.setText("Nombre");

        idJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idJLabel.setText("ID");

        cedulaJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cedulaJLabel.setText("Cedula");

        correoPersonalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoPersonalJLabel.setText("Correo Personal");

        descripcionJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        descripcionJLabel.setText("Descripciòn");

        btnAgregarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnAgregarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarJButton.setText("Agregar");
        btnAgregarJButton.setBorder(null);
        btnAgregarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarJButtonMouseClicked(evt);
            }
        });

        btnCancelarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnCancelarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarJButton.setText("Cancelar");
        btnCancelarJButton.setBorder(null);
        btnCancelarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoJPanelLayout = new javax.swing.GroupLayout(contenidoJPanel);
        contenidoJPanel.setLayout(contenidoJPanelLayout);
        contenidoJPanelLayout.setHorizontalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(btnAgregarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ingreseSiguientesDatosJLabel)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreJLabel)
                            .addComponent(idJLabel)
                            .addComponent(cedulaJLabel)
                            .addComponent(correoPersonalJLabel)
                            .addComponent(descripcionJLabel))
                        .addGap(60, 60, 60)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entadaDescripcionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        contenidoJPanelLayout.setVerticalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addComponent(ingreseSiguientesDatosJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreJLabel)
                            .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idJLabel)
                            .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cedulaJLabel)
                            .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(correoPersonalJLabel))
                    .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(descripcionJLabel))
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(entadaDescripcionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        fondoJPanel.add(contenidoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 700, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarJButtonMouseClicked
        // TODO add your handling code here:
        PersonaExterna[] personasActualizadas = personaExternaControlador.procesoControladorPersonaExterna();
        if (personasActualizadas != null && vistaPersonaExterna != null) {
            vistaPersonaExterna.getPersonaExternaPanel().actualizarTabla(personasActualizadas);
        }
    }//GEN-LAST:event_btnAgregarJButtonMouseClicked

    private void btnCancelarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarJButtonMouseClicked
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cancelar?", "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose(); // Cierra la ventana actual
        }   
        
    }//GEN-LAST:event_btnCancelarJButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    public String getEntradaNombreJTextField() {
        return entradaNombreJTextField.getText();
    }

    public String getEntradaIdJTextField() {
        return entradaIdJTextField.getText();
    }

    public String getEntradaCedulaJTextField() {
        return entradaCedulaJTextField.getText();
    }

    public String getEntradaCorreoPersonalJTextField() {
        return entradaCorreoPersonalJTextField.getText();
    }

    public String getEntradaDescripcionJTextField() {
        return entadaDescripcionJTextField.getText();
    }

    public void mostrarMensajeExito(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarMensajeError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarJButton;
    private javax.swing.JButton btnCancelarJButton;
    private javax.swing.JLabel cedulaJLabel;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JLabel correoPersonalJLabel;
    private javax.swing.JLabel descripcionJLabel;
    private javax.swing.JTextField entadaDescripcionJTextField;
    private javax.swing.JTextField entradaCedulaJTextField;
    private javax.swing.JTextField entradaCorreoPersonalJTextField;
    private javax.swing.JTextField entradaIdJTextField;
    private javax.swing.JTextField entradaNombreJTextField;
    private javax.swing.JPanel fondoJPanel;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel ingreseSiguientesDatosJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JPanel toorbarJPanel;
    // End of variables declaration//GEN-END:variables
}