
package com.mycompany.vistas.sistema;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.mycompany.controladores.ProfesorControlador;

public class ProfesorVista extends javax.swing.JFrame {

    /**
     * Creates new form ProfesoresVista
     */
    private ProfesorControlador profesorControlador;

    public ProfesorVista() {
        initComponents();
        profesorControlador = new ProfesorControlador(this);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoJPanel = new javax.swing.JPanel();
        toolbarJPanel = new javax.swing.JPanel();
        profesoresJLabel = new javax.swing.JLabel();
        contenidoJPanel = new javax.swing.JPanel();
        ingreseLosSiguientesDatosJLabel = new javax.swing.JLabel();
        nombreJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        cedulaJLabel = new javax.swing.JLabel();
        correoInstitucionalJLabel = new javax.swing.JLabel();
        correoPersonalJLabel = new javax.swing.JLabel();
        sueldoJLabel = new javax.swing.JLabel();
        dedicacionJLabel = new javax.swing.JLabel();
        escalafonJLabel = new javax.swing.JLabel();
        entradaNombreJTextField = new javax.swing.JTextField();
        entradaIdJTextField = new javax.swing.JTextField();
        entradaCedulaJTextField = new javax.swing.JTextField();
        entradaCorreoInstitucionalJTextField = new javax.swing.JTextField();
        entradaCorreoPersonalJTextField = new javax.swing.JTextField();
        entradaSueldoJTextField = new javax.swing.JTextField();
        entradaDedicacionJTextField = new javax.swing.JTextField();
        entradaEscalafonJComboBox = new javax.swing.JComboBox<>();
        btnAgregarJButton1 = new javax.swing.JButton();
        btnCancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        profesoresJLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        profesoresJLabel.setForeground(new java.awt.Color(255, 255, 255));
        profesoresJLabel.setText("PROFESORES");

        javax.swing.GroupLayout toolbarJPanelLayout = new javax.swing.GroupLayout(toolbarJPanel);
        toolbarJPanel.setLayout(toolbarJPanelLayout);
        toolbarJPanelLayout.setHorizontalGroup(
            toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(profesoresJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toolbarJPanelLayout.setVerticalGroup(
            toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarJPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(profesoresJLabel)
                .addGap(32, 32, 32))
        );

        fondoJPanel.add(toolbarJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, -1));

        contenidoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        ingreseLosSiguientesDatosJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ingreseLosSiguientesDatosJLabel.setText("INGRESE LOS SIGUIENTES DATOS");

        nombreJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombreJLabel.setText("Nombre");

        idJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idJLabel.setText("ID");

        cedulaJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cedulaJLabel.setText("Cedula");

        correoInstitucionalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoInstitucionalJLabel.setText("Correo Institucional");

        correoPersonalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoPersonalJLabel.setText("Correo Personal");

        sueldoJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        sueldoJLabel.setText("Sueldo");

        dedicacionJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        dedicacionJLabel.setText("Dedicación");

        escalafonJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        escalafonJLabel.setText("Escalafón");

        entradaNombreJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        entradaEscalafonJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRINCIPAL", "AGREGADO", "AUXILIAR", " " }));

        btnAgregarJButton1.setBackground(new java.awt.Color(41, 160, 197));
        btnAgregarJButton1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarJButton1.setText("Agregar");
        btnAgregarJButton1.setBorder(null);
        btnAgregarJButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarJButton1MouseClicked(evt);
            }
        });

        btnCancelarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnCancelarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarJButton.setText("Cancelar");
        btnCancelarJButton.setBorder(null);
        btnCancelarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoJPanelLayout = new javax.swing.GroupLayout(contenidoJPanel);
        contenidoJPanel.setLayout(contenidoJPanelLayout);
        contenidoJPanelLayout.setHorizontalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(idJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(cedulaJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(nombreJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(correoPersonalJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(correoInstitucionalJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(entradaCorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(sueldoJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaSueldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dedicacionJLabel)
                                    .addComponent(escalafonJLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entradaDedicacionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entradaEscalafonJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(158, 158, 158))
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingreseLosSiguientesDatosJLabel)
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addComponent(btnAgregarJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        contenidoJPanelLayout.setVerticalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addComponent(ingreseLosSiguientesDatosJLabel)
                .addGap(21, 21, 21)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJLabel)
                    .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJLabel)
                    .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaJLabel)
                    .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoInstitucionalJLabel)
                    .addComponent(entradaCorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoPersonalJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaSueldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldoJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dedicacionJLabel)
                    .addComponent(entradaDedicacionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escalafonJLabel)
                    .addComponent(entradaEscalafonJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        fondoJPanel.add(contenidoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 700, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarJButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCancelarJButtonMouseClicked

    private void btnAgregarJButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarJButton1MouseClicked
        // TODO add your handling code here:
        profesorControlador.procesoControladorProfesor();
    }//GEN-LAST:event_btnAgregarJButton1MouseClicked

    /**
     * @param args the command line arguments
     */
   
     public String getEntradaNombreJTextField() {
        return entradaNombreJTextField.getText();
    }
    
    public String getEntradaIdJTextField() {
        return entradaIdJTextField.getText();
    }

    public String getEntradaCedulaJTextField() {
        return entradaCedulaJTextField.getText();
    }

    public String getEntradaCorreoInstitucionalJTextField() {
        return entradaCorreoInstitucionalJTextField.getText();
    }

    public String getEntradaCorreoPersonalJTextField() {
        return entradaCorreoPersonalJTextField.getText();
    }

    public String getEntradaSueldoJTextField() {
        return entradaSueldoJTextField.getText();
    }

    public String getEntradaDedicacionJTextField() {
        return entradaDedicacionJTextField.getText();
    }

    public String getEntradaEscalafonJComboBox() {
        return (String) entradaEscalafonJComboBox.getSelectedItem();
    }

    public void mostrarMensajeExito(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarMensajeError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarJButton1;
    private javax.swing.JButton btnCancelarJButton;
    private javax.swing.JLabel cedulaJLabel;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JLabel correoInstitucionalJLabel;
    private javax.swing.JLabel correoPersonalJLabel;
    private javax.swing.JLabel dedicacionJLabel;
    private javax.swing.JTextField entradaCedulaJTextField;
    private javax.swing.JTextField entradaCorreoInstitucionalJTextField;
    private javax.swing.JTextField entradaCorreoPersonalJTextField;
    private javax.swing.JTextField entradaDedicacionJTextField;
    private javax.swing.JComboBox<String> entradaEscalafonJComboBox;
    private javax.swing.JTextField entradaIdJTextField;
    private javax.swing.JTextField entradaNombreJTextField;
    private javax.swing.JTextField entradaSueldoJTextField;
    private javax.swing.JLabel escalafonJLabel;
    private javax.swing.JPanel fondoJPanel;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel ingreseLosSiguientesDatosJLabel;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JLabel profesoresJLabel;
    private javax.swing.JLabel sueldoJLabel;
    private javax.swing.JPanel toolbarJPanel;
    // End of variables declaration//GEN-END:variables
}
