/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistas.sistema;
import com.mycompany.controladores.TrabajadorControlador;
import com.mycompany.itrabajador.Trabajador;
import com.mycompany.vistas.MainWindow;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ibarr
 */
public class TrabajadorVista extends javax.swing.JFrame {

    /**
     * Creates new form TrabajadoresVista
     */
    private TrabajadorControlador trabajadorControlador;
    private MainWindow vistaTrabajador;
    // VARIABLES PARA MANEJAR EL MODO DE ACTUALIZACIÓN
    private boolean modoActualizacion = false;
    private int idTrabajadorActualizar = -1;

    public TrabajadorVista(MainWindow vistaTrabajador) {
        initComponents();
        trabajadorControlador = new TrabajadorControlador(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.vistaTrabajador = vistaTrabajador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPrincipalJPanel = new javax.swing.JPanel();
        toorbarJPanel = new javax.swing.JPanel();
        trabajadoresJLabel = new javax.swing.JLabel();
        contenidoJPanel = new javax.swing.JPanel();
        ingreseSiguientesDatosLabel = new javax.swing.JLabel();
        nombreJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        correoPersonalJLabel = new javax.swing.JLabel();
        correoInstitucionalJLabel = new javax.swing.JLabel();
        CedulaLabel = new javax.swing.JLabel();
        sueldoJLabel = new javax.swing.JLabel();
        GremioJLabel = new javax.swing.JLabel();
        entradaNombreJTextField = new javax.swing.JTextField();
        entradaIdJTextField = new javax.swing.JTextField();
        entradaCorreoPersonalJTextField = new javax.swing.JTextField();
        entradaCorreoInstitucionalJTextField = new javax.swing.JTextField();
        entradaCedulaJTextField = new javax.swing.JTextField();
        entradaSueldoJTextField = new javax.swing.JTextField();
        entradaGremioJTextField = new javax.swing.JTextField();
        btnAgregarJButton = new javax.swing.JButton();
        btnCancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toorbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        trabajadoresJLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        trabajadoresJLabel.setForeground(new java.awt.Color(255, 255, 255));
        trabajadoresJLabel.setText("TRABAJADORES");

        javax.swing.GroupLayout toorbarJPanelLayout = new javax.swing.GroupLayout(toorbarJPanel);
        toorbarJPanel.setLayout(toorbarJPanelLayout);
        toorbarJPanelLayout.setHorizontalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toorbarJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(trabajadoresJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toorbarJPanelLayout.setVerticalGroup(
            toorbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toorbarJPanelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(trabajadoresJLabel)
                .addGap(36, 36, 36))
        );

        contenidoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        ingreseSiguientesDatosLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ingreseSiguientesDatosLabel.setText("INGRESE LOS SIGUIENTES DATOS");

        nombreJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombreJLabel.setText("Nombre");

        idJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        idJLabel.setText("ID");

        correoPersonalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoPersonalJLabel.setText("Correo Personal");

        correoInstitucionalJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correoInstitucionalJLabel.setText("Correo Institucional");

        CedulaLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CedulaLabel.setText("Cedula");

        sueldoJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        sueldoJLabel.setText("Sueldo");

        GremioJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        GremioJLabel.setText("Gremio");

        btnAgregarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnAgregarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarJButton.setText("Agregar");
        btnAgregarJButton.setBorder(null);
        btnAgregarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarJButtonMouseClicked(evt);
            }
        });

        btnCancelarJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnCancelarJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarJButton.setText("Cancelar");
        btnCancelarJButton.setBorder(null);
        btnCancelarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoJPanelLayout = new javax.swing.GroupLayout(contenidoJPanel);
        contenidoJPanel.setLayout(contenidoJPanelLayout);
        contenidoJPanelLayout.setHorizontalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingreseSiguientesDatosLabel)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(correoInstitucionalJLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(correoPersonalJLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CedulaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idJLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreJLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                    .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(GremioJLabel)
                                        .addComponent(sueldoJLabel))
                                    .addGap(101, 101, 101)))
                            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnAgregarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaSueldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaGremioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        contenidoJPanelLayout.setVerticalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoJPanelLayout.createSequentialGroup()
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ingreseSiguientesDatosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entradaNombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaCorreoPersonalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(nombreJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoPersonalJLabel)))
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(correoInstitucionalJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CedulaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sueldoJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GremioJLabel))
                    .addGroup(contenidoJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entradaCorreoInstitucionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(entradaCedulaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entradaSueldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entradaGremioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoPrincipalJPanelLayout = new javax.swing.GroupLayout(fondoPrincipalJPanel);
        fondoPrincipalJPanel.setLayout(fondoPrincipalJPanelLayout);
        fondoPrincipalJPanelLayout.setHorizontalGroup(
            fondoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toorbarJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenidoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoPrincipalJPanelLayout.setVerticalGroup(
            fondoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPrincipalJPanelLayout.createSequentialGroup()
                .addComponent(toorbarJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPrincipalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPrincipalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarJButtonMouseClicked
        // TODO add your handling code here:
        if (modoActualizacion) {
            Trabajador[] trabajadoresActualizados = trabajadorControlador.procesoActualizarTrabajador();
            if (trabajadoresActualizados != null) {
                // ACTUALIZAR LA TABLA EN EL PANEL PRINCIPAL
                vistaTrabajador.getTrabajadoresPanel().actualizarTabla(trabajadoresActualizados);
                // CERRAR LA VENTANA DE ACTUALIZACIÓN
                this.dispose();
            }
        } else {
            Trabajador[] nuevosTrabjadores = trabajadorControlador.procesoControladorTrabajador();
            if (nuevosTrabjadores != null) {
                // ACTUALIZAR LA TABLA EN EL PANEL PRINCIPAL
                vistaTrabajador.getTrabajadoresPanel().actualizarTabla(nuevosTrabjadores);
                // CERRAR LA VENTANA DE REGISTRO
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAgregarJButtonMouseClicked

    private void btnCancelarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarJButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarJButtonMouseClicked

    /**
     * @param args the command line arguments
     */
   
    public String getEntradaNombreJTextField() {
        return entradaNombreJTextField.getText();
    }

    public String getEntradaIdJTextField() {
        return entradaIdJTextField.getText();
    }

    public String getEntradaCedulaJTextField() {
        return entradaCedulaJTextField.getText();
    }

    public String getEntradaCorreoInstitucionalJTextField() {
        return entradaCorreoInstitucionalJTextField.getText();
    }

    public String getEntradaCorreoPersonalJTextField() {
        return entradaCorreoPersonalJTextField.getText();
    }

    public String getEntradaSueldoJTextField() {
        return entradaSueldoJTextField.getText();
    }

    public String getEntradaGremioJTextField() {
        return entradaGremioJTextField.getText();
    }

    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "", JOptionPane.ERROR_MESSAGE);
    }

    // MÉTODO PARA CONFIGURAR EL MODO DE ACTUALIZACIÓN
    public void configurarModoActualizacion(Trabajador trabajador) {
        this.modoActualizacion = true;
        this.idTrabajadorActualizar = trabajador.getId();
        
        // PRECARGAR LOS DATOS EN LOS CAMPOS
        entradaNombreJTextField.setText(trabajador.getNombre());
        entradaIdJTextField.setText(String.valueOf(trabajador.getId()));
        entradaIdJTextField.setEditable(false); // NO PERMITIR EDITAR EL ID
        entradaCedulaJTextField.setText(trabajador.getCedula());
        entradaCorreoInstitucionalJTextField.setText(trabajador.getCorreoInstitucional());
        entradaCorreoPersonalJTextField.setText(trabajador.getCorreoPersonal());
        entradaSueldoJTextField.setText(String.valueOf(trabajador.getSueldo()));
        entradaGremioJTextField.setText(trabajador.getGremio());
        
        // CAMBIAR EL TEXTO DEL BOTÓN
        btnAgregarJButton.setText("Actualizar");
    }
    
    // MÉTODO PARA VERIFICAR SI ESTÁ EN MODO ACTUALIZACIÓN
    public boolean esModoActualizacion() {
        return modoActualizacion;
    }
    
    // MÉTODO PARA OBTENER EL ID DEL TRABAJADOR A ACTUALIZAR
    public int getIdTrabajadorActualizar() {
        return idTrabajadorActualizar;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CedulaLabel;
    private javax.swing.JLabel GremioJLabel;
    private javax.swing.JButton btnAgregarJButton;
    private javax.swing.JButton btnCancelarJButton;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JLabel correoInstitucionalJLabel;
    private javax.swing.JLabel correoPersonalJLabel;
    private javax.swing.JTextField entradaCedulaJTextField;
    private javax.swing.JTextField entradaCorreoInstitucionalJTextField;
    private javax.swing.JTextField entradaCorreoPersonalJTextField;
    private javax.swing.JTextField entradaGremioJTextField;
    private javax.swing.JTextField entradaIdJTextField;
    private javax.swing.JTextField entradaNombreJTextField;
    private javax.swing.JTextField entradaSueldoJTextField;
    private javax.swing.JPanel fondoPrincipalJPanel;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel ingreseSiguientesDatosLabel;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JLabel sueldoJLabel;
    private javax.swing.JPanel toorbarJPanel;
    private javax.swing.JLabel trabajadoresJLabel;
    // End of variables declaration//GEN-END:variables
}