// @author William

package com.mycompany.vistas;

public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJPanel = new javax.swing.JPanel();
        portadaSAJPanel = new javax.swing.JPanel();
        contenidoLoginJPanel = new javax.swing.JPanel();
        sistemaAcademicoJLabel = new javax.swing.JLabel();
        usuarioJLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        portadaSAJPanel.setBackground(new java.awt.Color(18, 63, 90));
        portadaSAJPanel.setPreferredSize(new java.awt.Dimension(300, 550));

        javax.swing.GroupLayout portadaSAJPanelLayout = new javax.swing.GroupLayout(portadaSAJPanel);
        portadaSAJPanel.setLayout(portadaSAJPanelLayout);
        portadaSAJPanelLayout.setHorizontalGroup(
            portadaSAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        portadaSAJPanelLayout.setVerticalGroup(
            portadaSAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        bgJPanel.add(portadaSAJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        sistemaAcademicoJLabel.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        sistemaAcademicoJLabel.setText("SISTEMA ACADÉMICO");

        usuarioJLabel.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        usuarioJLabel.setText("USUARIO");

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Ingrese su usuario");

        javax.swing.GroupLayout contenidoLoginJPanelLayout = new javax.swing.GroupLayout(contenidoLoginJPanel);
        contenidoLoginJPanel.setLayout(contenidoLoginJPanelLayout);
        contenidoLoginJPanelLayout.setHorizontalGroup(
            contenidoLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLoginJPanelLayout.createSequentialGroup()
                .addGroup(contenidoLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLoginJPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(sistemaAcademicoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLoginJPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(contenidoLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioJLabel)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        contenidoLoginJPanelLayout.setVerticalGroup(
            contenidoLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLoginJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(sistemaAcademicoJLabel)
                .addGap(34, 34, 34)
                .addComponent(usuarioJLabel)
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        bgJPanel.add(contenidoLoginJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgJPanel;
    private javax.swing.JPanel contenidoLoginJPanel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel portadaSAJPanel;
    private javax.swing.JLabel sistemaAcademicoJLabel;
    private javax.swing.JLabel usuarioJLabel;
    // End of variables declaration//GEN-END:variables
}
