package com.mycompany.vistas;

import javax.swing.JFrame;
import javax.swing.UIManager;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.controladores.PersonaExternaControlador;
import com.mycompany.controladores.EstudianteControlador; // IMPORT AGREGADO PARA ESTUDIANTES
import com.mycompany.ipersonasexternas.PersonaExterna; // IMPORT AGREGADO PARA FUNCIONALIDAD DE BÚSQUEDA
import com.mycompany.iestudiantes.Estudiante; // IMPORT AGREGADO PARA ESTUDIANTES
import com.mycompany.vistas.paneles.*;

import com.mycompany.vistas.sistema.*;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindows
     */
    private PersonaExternaPanel personaExternaPanel;
    private PersonaExternaControlador personaExternaControlador; // Agregar referencia al controlador
    
    // AGREGAR VARIABLES PARA ESTUDIANTES
    private EstudiantePanel estudiantePanel;
    private EstudianteControlador estudianteControlador;

    public MainWindow() {
        initComponents();
        PersonaExternaVista personaExternaVista = new PersonaExternaVista(this);
        personaExternaControlador = new PersonaExternaControlador(personaExternaVista);
        personaExternaPanel = new PersonaExternaPanel(personaExternaControlador);
        
        // INICIALIZAR COMPONENTES DE ESTUDIANTES
        EstudianteVista estudianteVista = new EstudianteVista(this); // PASAR REFERENCIA DE MAINWINDOW
        estudianteControlador = new EstudianteControlador(estudianteVista);
        estudiantePanel = new EstudiantePanel(estudianteControlador);
        
        // setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // btnPersonaExternaJButton.putClientProperty( "JButton.buttonType", "roundRect" );
        btnPersonaExternaJButton.putClientProperty("JButton.arc", 999);
        btnTrabajadoresJButton.putClientProperty("JButton.arc", 999);
        btnEstudiantesJButton.putClientProperty("JButton.arc", 999);
        btnProfesoresJButton.putClientProperty("JButton.arc", 999);
        btnPersonaExternaJButton.setBorderPainted(true);
        btnTrabajadoresJButton.setBorderPainted(true);
        btnEstudiantesJButton.setBorderPainted(true);
        btnProfesoresJButton.setBorderPainted(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPrincipalJPanel1 = new javax.swing.JPanel();
        fondoMenuJPanel2 = new javax.swing.JPanel();
        headerJPanel = new javax.swing.JPanel();
        menuItemJPanel = new javax.swing.JPanel();
        btnInicioJPanel = new javax.swing.JPanel();
        inicioJLabel = new javax.swing.JLabel();
        btnConfiguracionJPanel = new javax.swing.JPanel();
        configuracionJLabel = new javax.swing.JLabel();
        btnAcercaDeJPanel = new javax.swing.JPanel();
        acercaDeJLabel = new javax.swing.JLabel();
        btnSalirJPanel = new javax.swing.JPanel();
        salirJLabel = new javax.swing.JLabel();
        toolbarJPanel = new javax.swing.JPanel();
        bienvenidoAlSistemaAcademicoJLabel = new javax.swing.JLabel();
        buscarBarraJTextField = new javax.swing.JTextField();
        btnRegistrarJLabel = new javax.swing.JLabel();
        itemRolesPTEPJComboBox = new javax.swing.JComboBox<>();
        contenidoDeBotonesJPanel = new javax.swing.JPanel();
        btnPersonaExternaJButton = new javax.swing.JButton();
        btnTrabajadoresJButton = new javax.swing.JButton();
        btnEstudiantesJButton = new javax.swing.JButton();
        btnProfesoresJButton = new javax.swing.JButton();
        contenidoPrincipalJPanel = new javax.swing.JPanel();
        imgUniversidadJLabel = new javax.swing.JLabel();
        UniversidadSanWilliamJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPrincipalJPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoMenuJPanel2.setBackground(new java.awt.Color(18, 63, 90));

        headerJPanel.setBackground(new java.awt.Color(29, 107, 140));

        javax.swing.GroupLayout headerJPanelLayout = new javax.swing.GroupLayout(headerJPanel);
        headerJPanel.setLayout(headerJPanelLayout);
        headerJPanelLayout.setHorizontalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        headerJPanelLayout.setVerticalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        menuItemJPanel.setBackground(new java.awt.Color(18, 63, 90));
        menuItemJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicioJPanel.setBackground(new java.awt.Color(18, 63, 90));

        inicioJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        inicioJLabel.setForeground(new java.awt.Color(255, 255, 255));
        inicioJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicioJLabel.setText("Inicio");

        javax.swing.GroupLayout btnInicioJPanelLayout = new javax.swing.GroupLayout(btnInicioJPanel);
        btnInicioJPanel.setLayout(btnInicioJPanelLayout);
        btnInicioJPanelLayout.setHorizontalGroup(
            btnInicioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(inicioJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnInicioJPanelLayout.setVerticalGroup(
            btnInicioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicioJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuItemJPanel.add(btnInicioJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 30));

        btnConfiguracionJPanel.setBackground(new java.awt.Color(18, 63, 90));

        configuracionJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        configuracionJLabel.setForeground(new java.awt.Color(255, 255, 255));
        configuracionJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configuracionJLabel.setText("Configuración");

        javax.swing.GroupLayout btnConfiguracionJPanelLayout = new javax.swing.GroupLayout(btnConfiguracionJPanel);
        btnConfiguracionJPanel.setLayout(btnConfiguracionJPanelLayout);
        btnConfiguracionJPanelLayout.setHorizontalGroup(
            btnConfiguracionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfiguracionJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(configuracionJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnConfiguracionJPanelLayout.setVerticalGroup(
            btnConfiguracionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfiguracionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configuracionJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuItemJPanel.add(btnConfiguracionJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 30));

        btnAcercaDeJPanel.setBackground(new java.awt.Color(18, 63, 90));

        acercaDeJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        acercaDeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        acercaDeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        acercaDeJLabel.setText("Acerca de");

        javax.swing.GroupLayout btnAcercaDeJPanelLayout = new javax.swing.GroupLayout(btnAcercaDeJPanel);
        btnAcercaDeJPanel.setLayout(btnAcercaDeJPanelLayout);
        btnAcercaDeJPanelLayout.setHorizontalGroup(
            btnAcercaDeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAcercaDeJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(acercaDeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAcercaDeJPanelLayout.setVerticalGroup(
            btnAcercaDeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAcercaDeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acercaDeJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuItemJPanel.add(btnAcercaDeJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 30));

        btnSalirJPanel.setBackground(new java.awt.Color(18, 63, 90));

        salirJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        salirJLabel.setForeground(new java.awt.Color(255, 255, 255));
        salirJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salirJLabel.setText("Salir");

        javax.swing.GroupLayout btnSalirJPanelLayout = new javax.swing.GroupLayout(btnSalirJPanel);
        btnSalirJPanel.setLayout(btnSalirJPanelLayout);
        btnSalirJPanelLayout.setHorizontalGroup(
            btnSalirJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(salirJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnSalirJPanelLayout.setVerticalGroup(
            btnSalirJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salirJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuItemJPanel.add(btnSalirJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, -1));

        javax.swing.GroupLayout fondoMenuJPanel2Layout = new javax.swing.GroupLayout(fondoMenuJPanel2);
        fondoMenuJPanel2.setLayout(fondoMenuJPanel2Layout);
        fondoMenuJPanel2Layout.setHorizontalGroup(
            fondoMenuJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuItemJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        fondoMenuJPanel2Layout.setVerticalGroup(
            fondoMenuJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoMenuJPanel2Layout.createSequentialGroup()
                .addComponent(headerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuItemJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        headerJPanel.getAccessibleContext().setAccessibleName("");

        fondoPrincipalJPanel1.add(fondoMenuJPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        toolbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        bienvenidoAlSistemaAcademicoJLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bienvenidoAlSistemaAcademicoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoAlSistemaAcademicoJLabel.setText("BIENVENIDO AL SISTEMA ACADÉMICO");

        buscarBarraJTextField.setBackground(new java.awt.Color(204, 204, 204));
        buscarBarraJTextField.setText("Buscar...");
        // AGREGAR LISTENER PARA LA FUNCIONALIDAD DE BÚSQUEDA
        buscarBarraJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.buscarPersonaExterna();
            }
        });
        // AGREGAR LISTENER PARA LIMPIAR EL PLACEHOLDER AL HACER CLIC
        buscarBarraJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (buscarBarraJTextField.getText().equals("Buscar...")) {
                    buscarBarraJTextField.setText("");
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (buscarBarraJTextField.getText().isEmpty()) {
                    buscarBarraJTextField.setText("Buscar...");
                }
            }
        });

        btnRegistrarJLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnRegistrarJLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarJLabel.setText("Registrar");
        btnRegistrarJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarJLabelMouseClicked(evt);
            }
        });

        itemRolesPTEPJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Externa", "Estudiante", "Trabajador", "Profesor", "Decano" }));
        itemRolesPTEPJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRolesPTEPJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolbarJPanelLayout = new javax.swing.GroupLayout(toolbarJPanel);
        toolbarJPanel.setLayout(toolbarJPanelLayout);
        toolbarJPanelLayout.setHorizontalGroup(
            toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bienvenidoAlSistemaAcademicoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarBarraJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarJPanelLayout.createSequentialGroup()
                        .addComponent(btnRegistrarJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemRolesPTEPJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        toolbarJPanelLayout.setVerticalGroup(
            toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenidoAlSistemaAcademicoJLabel)
                    .addGroup(toolbarJPanelLayout.createSequentialGroup()
                        .addComponent(buscarBarraJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemRolesPTEPJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarJLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondoPrincipalJPanel1.add(toolbarJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 730, -1));

        contenidoDeBotonesJPanel.setPreferredSize(new java.awt.Dimension(100, 50));

        btnPersonaExternaJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnPersonaExternaJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonaExternaJButton.setText("Persona Externa");
        btnPersonaExternaJButton.setBorder(null);
        btnPersonaExternaJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        btnPersonaExternaJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonaExternaJButtonMouseClicked(evt);
            }
        });

        btnTrabajadoresJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnTrabajadoresJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnTrabajadoresJButton.setText("Trabajadores");
        btnTrabajadoresJButton.setBorder(null);
        btnTrabajadoresJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        btnTrabajadoresJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrabajadoresJButtonMouseClicked(evt);
            }
        });

        btnEstudiantesJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnEstudiantesJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnEstudiantesJButton.setText("Estudiantes");
        btnEstudiantesJButton.setBorder(null);
        btnEstudiantesJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        btnEstudiantesJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstudiantesJButtonMouseClicked(evt);
            }
        });

        btnProfesoresJButton.setBackground(new java.awt.Color(41, 160, 197));
        btnProfesoresJButton.setForeground(new java.awt.Color(255, 255, 255));
        btnProfesoresJButton.setText("Profesores");
        btnProfesoresJButton.setBorder(null);
        btnProfesoresJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        btnProfesoresJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfesoresJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoDeBotonesJPanelLayout = new javax.swing.GroupLayout(contenidoDeBotonesJPanel);
        contenidoDeBotonesJPanel.setLayout(contenidoDeBotonesJPanelLayout);
        contenidoDeBotonesJPanelLayout.setHorizontalGroup(
            contenidoDeBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoDeBotonesJPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnPersonaExternaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrabajadoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstudiantesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfesoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        contenidoDeBotonesJPanelLayout.setVerticalGroup(
            contenidoDeBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoDeBotonesJPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(contenidoDeBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersonaExternaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrabajadoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudiantesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfesoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fondoPrincipalJPanel1.add(contenidoDeBotonesJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 730, -1));

        contenidoPrincipalJPanel.setBackground(new java.awt.Color(255, 255, 255));

        imgUniversidadJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUniversidadJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/imagesU.jpeg"))); // NOI18N

        UniversidadSanWilliamJLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        UniversidadSanWilliamJLabel.setText("UNIVERSIDAD DE SAN WILLIAM");

        javax.swing.GroupLayout contenidoPrincipalJPanelLayout = new javax.swing.GroupLayout(contenidoPrincipalJPanel);
        contenidoPrincipalJPanel.setLayout(contenidoPrincipalJPanelLayout);
        contenidoPrincipalJPanelLayout.setHorizontalGroup(
            contenidoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoPrincipalJPanelLayout.createSequentialGroup()
                .addGroup(contenidoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoPrincipalJPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(UniversidadSanWilliamJLabel))
                    .addGroup(contenidoPrincipalJPanelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(imgUniversidadJLabel)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        contenidoPrincipalJPanelLayout.setVerticalGroup(
            contenidoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPrincipalJPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(UniversidadSanWilliamJLabel)
                .addGap(18, 18, 18)
                .addComponent(imgUniversidadJLabel)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        fondoPrincipalJPanel1.add(contenidoPrincipalJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 730, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPrincipalJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPrincipalJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRolesPTEPJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRolesPTEPJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRolesPTEPJComboBoxActionPerformed

    // PARA MANEJAR EL EVENTO DE CLIC EN EL LABEL "Registrar"
    private void btnRegistrarJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarJLabelMouseClicked
        // TODO add your handling code here:
        String itemSeleccionado = (String) itemRolesPTEPJComboBox.getSelectedItem();

        // SE LLAMA A LA VENTANA DE REGISTRO SEGÚN EL ITEM SELECCIONADO
        switch (itemSeleccionado) {
            case "Persona Externa":
                PersonaExternaVista personaExternaVista = new PersonaExternaVista(this);
                personaExternaVista.setVisible(true);
                break;
            case "Estudiante":
                EstudianteVista estudianteVista = new EstudianteVista(this); // PASAR REFERENCIA DE MAINWINDOW
                estudianteVista.setVisible(true);
                break;
            case "Trabajador":
                new TrabajadorVista().setVisible(true);
                break;
            case "Profesor":
                new ProfesorVista().setVisible(true);
                break;
            case "Decano":
                new DecanoVista().setVisible(true);
                break;
            default:    
                // Manejar el caso por defecto si es necesario
                break;
        }
    }//GEN-LAST:event_btnRegistrarJLabelMouseClicked

    /* public javax.swing.JPanel getContenidoPrincipalJPanel() {
        return contenidoPrincipalJPanel;
    } */

    // PARA MOSTRAR EL PANEL SELECCIONADO EN EL CONTENIDO PRINCIPAL
    public void mostrarPanel(javax.swing.JPanel panel) {
        panel.setSize(730, 420);
        panel.setLocation(0, 0);
        contenidoPrincipalJPanel.removeAll();
        contenidoPrincipalJPanel.add(panel);
        contenidoPrincipalJPanel.revalidate();
        contenidoPrincipalJPanel.repaint();
    }

    // EVENTO PARA MANEJAR EL CLIC EN EL BOTÓN "Persona Externa"
    private void btnPersonaExternaJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonaExternaJButtonMouseClicked
        // TODO add your handling code here:
        mostrarPanel(personaExternaPanel);
        // ACTUALIZAR LA TABLA CON TODOS LOS DATOS ACTUALES USANDO EL CONTROLADOR EXISTENTE
        personaExternaPanel.actualizarTabla(personaExternaControlador.obtenerPersonasExternas());
        
        // LIMPIAR LA BARRA DE BÚSQUEDA AL MOSTRAR TODOS LOS DATOS
        if (!buscarBarraJTextField.getText().equals("Buscar...")) {
            buscarBarraJTextField.setText("Buscar...");
        }

    }//GEN-LAST:event_btnPersonaExternaJButtonMouseClicked

    // EVENTO PARA MANEJAR EL CLIC EN EL BOTÓN "Trabajadores"
    private void btnTrabajadoresJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadoresJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresJButtonMouseClicked

    // EVENTO PARA MANEJAR EL CLIC EN EL BOTÓN "Estudiantes"
    private void btnEstudiantesJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesJButtonMouseClicked
        // MOSTRAR EL PANEL DE ESTUDIANTES Y ACTUALIZAR LA TABLA
        mostrarPanel(estudiantePanel);
        // ACTUALIZAR LA TABLA CON LOS DATOS ACTUALES USANDO EL CONTROLADOR EXISTENTE
        estudiantePanel.actualizarTabla(estudianteControlador.obtenerEstudiantes());
    }//GEN-LAST:event_btnEstudiantesJButtonMouseClicked

    // EVENTO PARA MANEJAR EL CLIC EN EL BOTÓN "Profesores"
    private void btnProfesoresJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfesoresJButtonMouseClicked

    // MÉTODO PARA BUSCAR PERSONA EXTERNA O ESTUDIANTE POR ID
    private void buscarPersonaExterna() {
        String textoBusqueda = buscarBarraJTextField.getText().trim();
        
        // VERIFICAR QUE NO ESTÉ VACÍO Y NO SEA EL PLACEHOLDER
        if (textoBusqueda.isEmpty() || textoBusqueda.equals("Buscar...")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor ingrese un ID para buscar.", 
                "Campo vacío", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // CONVERTIR EL TEXTO A NÚMERO
            int id = Integer.parseInt(textoBusqueda);
            
            // BUSCAR PRIMERO EN PERSONAS EXTERNAS
            PersonaExterna personaEncontrada = personaExternaControlador.buscarPersonaExternaPorId(id);
            
            if (personaEncontrada != null) {
                // MOSTRAR EL PANEL DE PERSONA EXTERNA SI NO ESTÁ VISIBLE
                mostrarPanel(personaExternaPanel);
                
                // MOSTRAR SOLO LA PERSONA ENCONTRADA EN LA TABLA
                personaExternaPanel.buscarYMostrarPersona(personaEncontrada);
                
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Persona Externa encontrada: " + personaEncontrada.getNombre(), 
                    "Búsqueda exitosa", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // SI NO SE ENCUENTRA EN PERSONAS EXTERNAS, BUSCAR EN ESTUDIANTES
            Estudiante estudianteEncontrado = estudianteControlador.obtenerEstudiantePorId(id);
            
            if (estudianteEncontrado != null) {
                // MOSTRAR EL PANEL DE ESTUDIANTES SI NO ESTÁ VISIBLE
                mostrarPanel(estudiantePanel);
                
                // MOSTRAR SOLO EL ESTUDIANTE ENCONTRADO EN LA TABLA
                estudiantePanel.buscarEstudiante(id);
                
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Estudiante encontrado: " + estudianteEncontrado.getNombre(), 
                    "Búsqueda exitosa", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "No se encontró ninguna persona o estudiante con el ID: " + id, 
                    "No encontrado", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor ingrese un número válido para el ID.", 
                "ID inválido", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    public PersonaExternaPanel getPersonaExternaPanel() {
        return personaExternaPanel;
    }

    // MÉTODO PARA OBTENER EL PANEL DE ESTUDIANTES
    public EstudiantePanel getEstudiantePanel() {
        return estudiantePanel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        FlatLightLaf.setup();
        UIManager.put( "Button.arc", 999 );
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "ProgressBar.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UniversidadSanWilliamJLabel;
    private javax.swing.JLabel acercaDeJLabel;
    private javax.swing.JLabel bienvenidoAlSistemaAcademicoJLabel;
    private javax.swing.JPanel btnAcercaDeJPanel;
    private javax.swing.JPanel btnConfiguracionJPanel;
    private javax.swing.JButton btnEstudiantesJButton;
    private javax.swing.JPanel btnInicioJPanel;
    private javax.swing.JButton btnPersonaExternaJButton;
    private javax.swing.JButton btnProfesoresJButton;
    private javax.swing.JLabel btnRegistrarJLabel;
    private javax.swing.JPanel btnSalirJPanel;
    private javax.swing.JButton btnTrabajadoresJButton;
    private javax.swing.JTextField buscarBarraJTextField;
    private javax.swing.JLabel configuracionJLabel;
    private javax.swing.JPanel contenidoDeBotonesJPanel;
    private javax.swing.JPanel contenidoPrincipalJPanel;
    private javax.swing.JPanel fondoMenuJPanel2;
    private javax.swing.JPanel fondoPrincipalJPanel1;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JLabel imgUniversidadJLabel;
    private javax.swing.JLabel inicioJLabel;
    private javax.swing.JComboBox<String> itemRolesPTEPJComboBox;
    private javax.swing.JPanel menuItemJPanel;
    private javax.swing.JLabel salirJLabel;
    private javax.swing.JPanel toolbarJPanel;
    // End of variables declaration//GEN-END:variables
}
