package com.mycompany.vistas;

import javax.swing.JFrame;
import com.mycompany.vistas.paneles.*;

import com.mycompany.vistas.sistema.*;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindows
     */
    public MainWindow() {
        initComponents();
        // setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPrincipalJPanel1 = new javax.swing.JPanel();
        fondoMenuJPanel2 = new javax.swing.JPanel();
        headerJPanel = new javax.swing.JPanel();
        menuItemJPanel = new javax.swing.JPanel();
        btnInicioJLabel = new javax.swing.JLabel();
        btnConfiguracionJLabel = new javax.swing.JLabel();
        btnAcercaDeJLabel = new javax.swing.JLabel();
        btnSalirJLabel = new javax.swing.JLabel();
        toolbarJPanel = new javax.swing.JPanel();
        bienvenidoAlSistemaAcademicoJLabel = new javax.swing.JLabel();
        buscarBarraJTextField = new javax.swing.JTextField();
        btnRegistrarJLabel = new javax.swing.JLabel();
        itemRolesPTEPJComboBox = new javax.swing.JComboBox<>();
        contenidoDeBotonesJPanel = new javax.swing.JPanel();
        personaExternaJButton = new javax.swing.JButton();
        trabajadoresJButton = new javax.swing.JButton();
        estudiantesJButton = new javax.swing.JButton();
        profesoresJButton = new javax.swing.JButton();
        contenidoPrincipalJPanel = new javax.swing.JPanel();
        imgUniversidadJLabel = new javax.swing.JLabel();
        UniversidadSanWilliamJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPrincipalJPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoMenuJPanel2.setBackground(new java.awt.Color(18, 63, 90));
        fondoMenuJPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJPanel.setBackground(new java.awt.Color(29, 107, 140));

        javax.swing.GroupLayout headerJPanelLayout = new javax.swing.GroupLayout(headerJPanel);
        headerJPanel.setLayout(headerJPanelLayout);
        headerJPanelLayout.setHorizontalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        headerJPanelLayout.setVerticalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        fondoMenuJPanel2.add(headerJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 130));
        headerJPanel.getAccessibleContext().setAccessibleName("");

        menuItemJPanel.setBackground(new java.awt.Color(18, 63, 90));

        btnInicioJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnInicioJLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnInicioJLabel.setText("Inicio");

        btnConfiguracionJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnConfiguracionJLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracionJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConfiguracionJLabel.setText("Configuración");

        btnAcercaDeJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAcercaDeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnAcercaDeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAcercaDeJLabel.setText("Acerca de");

        btnSalirJLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSalirJLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSalirJLabel.setText("Salir");

        javax.swing.GroupLayout menuItemJPanelLayout = new javax.swing.GroupLayout(menuItemJPanel);
        menuItemJPanel.setLayout(menuItemJPanelLayout);
        menuItemJPanelLayout.setHorizontalGroup(
            menuItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(menuItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalirJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcercaDeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfiguracionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicioJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        menuItemJPanelLayout.setVerticalGroup(
            menuItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItemJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnInicioJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfiguracionJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAcercaDeJLabel)
                .addGap(18, 18, 18)
                .addComponent(btnSalirJLabel)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        fondoMenuJPanel2.add(menuItemJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 420));

        fondoPrincipalJPanel1.add(fondoMenuJPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 550));

        toolbarJPanel.setBackground(new java.awt.Color(29, 107, 140));

        bienvenidoAlSistemaAcademicoJLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bienvenidoAlSistemaAcademicoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoAlSistemaAcademicoJLabel.setText("BIENVENIDO AL SISTEMA ACADÉMICO");

        buscarBarraJTextField.setBackground(new java.awt.Color(204, 204, 204));
        buscarBarraJTextField.setText("Buscar.....");

        btnRegistrarJLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnRegistrarJLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarJLabel.setText("Registrar");
        btnRegistrarJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarJLabelMouseClicked(evt);
            }
        });

        itemRolesPTEPJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Externa", "Estudiante", "Trabajador", "Profesor", "Decano" }));
        itemRolesPTEPJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRolesPTEPJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolbarJPanelLayout = new javax.swing.GroupLayout(toolbarJPanel);
        toolbarJPanel.setLayout(toolbarJPanelLayout);
        toolbarJPanelLayout.setHorizontalGroup(
            toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bienvenidoAlSistemaAcademicoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarBarraJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarJPanelLayout.createSequentialGroup()
                        .addComponent(btnRegistrarJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemRolesPTEPJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        toolbarJPanelLayout.setVerticalGroup(
            toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenidoAlSistemaAcademicoJLabel)
                    .addGroup(toolbarJPanelLayout.createSequentialGroup()
                        .addComponent(buscarBarraJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(toolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemRolesPTEPJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarJLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondoPrincipalJPanel1.add(toolbarJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 730, 80));

        contenidoDeBotonesJPanel.setPreferredSize(new java.awt.Dimension(100, 50));

        personaExternaJButton.setBackground(new java.awt.Color(41, 160, 197));
        personaExternaJButton.setForeground(new java.awt.Color(255, 255, 255));
        personaExternaJButton.setText("Persona Externa");
        personaExternaJButton.setBorder(null);
        personaExternaJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        personaExternaJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaExternaJButtonMouseClicked(evt);
            }
        });

        trabajadoresJButton.setBackground(new java.awt.Color(41, 160, 197));
        trabajadoresJButton.setForeground(new java.awt.Color(255, 255, 255));
        trabajadoresJButton.setText("Trabajadores");
        trabajadoresJButton.setBorder(null);
        trabajadoresJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        trabajadoresJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trabajadoresJButtonMouseClicked(evt);
            }
        });

        estudiantesJButton.setBackground(new java.awt.Color(41, 160, 197));
        estudiantesJButton.setForeground(new java.awt.Color(255, 255, 255));
        estudiantesJButton.setText("Estudiantes");
        estudiantesJButton.setBorder(null);
        estudiantesJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        estudiantesJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estudiantesJButtonMouseClicked(evt);
            }
        });

        profesoresJButton.setBackground(new java.awt.Color(41, 160, 197));
        profesoresJButton.setForeground(new java.awt.Color(255, 255, 255));
        profesoresJButton.setText("Profesores");
        profesoresJButton.setBorder(null);
        profesoresJButton.setPreferredSize(new java.awt.Dimension(83, 30));
        profesoresJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesoresJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contenidoDeBotonesJPanelLayout = new javax.swing.GroupLayout(contenidoDeBotonesJPanel);
        contenidoDeBotonesJPanel.setLayout(contenidoDeBotonesJPanelLayout);
        contenidoDeBotonesJPanelLayout.setHorizontalGroup(
            contenidoDeBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoDeBotonesJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(personaExternaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trabajadoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estudiantesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        contenidoDeBotonesJPanelLayout.setVerticalGroup(
            contenidoDeBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoDeBotonesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenidoDeBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estudiantesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personaExternaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trabajadoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesoresJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        fondoPrincipalJPanel1.add(contenidoDeBotonesJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 730, -1));

        contenidoPrincipalJPanel.setBackground(new java.awt.Color(255, 255, 255));

        imgUniversidadJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgUniversidadJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/imagesU.jpeg"))); // NOI18N

        UniversidadSanWilliamJLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        UniversidadSanWilliamJLabel.setText("UNIVERSIDAD DE SAN WILLIAM");

        javax.swing.GroupLayout contenidoPrincipalJPanelLayout = new javax.swing.GroupLayout(contenidoPrincipalJPanel);
        contenidoPrincipalJPanel.setLayout(contenidoPrincipalJPanelLayout);
        contenidoPrincipalJPanelLayout.setHorizontalGroup(
            contenidoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoPrincipalJPanelLayout.createSequentialGroup()
                .addGroup(contenidoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoPrincipalJPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(UniversidadSanWilliamJLabel))
                    .addGroup(contenidoPrincipalJPanelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(imgUniversidadJLabel)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        contenidoPrincipalJPanelLayout.setVerticalGroup(
            contenidoPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPrincipalJPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(UniversidadSanWilliamJLabel)
                .addGap(18, 18, 18)
                .addComponent(imgUniversidadJLabel)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        fondoPrincipalJPanel1.add(contenidoPrincipalJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 730, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPrincipalJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPrincipalJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRolesPTEPJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRolesPTEPJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRolesPTEPJComboBoxActionPerformed

    // PARA MANEJAR EL EVENTO DE CLIC EN EL LABEL "Registrar"
    private void btnRegistrarJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarJLabelMouseClicked
        // TODO add your handling code here:
        String itemSeleccionado = (String) itemRolesPTEPJComboBox.getSelectedItem();

        // SE LLAMA A LA VENTANA DE REGISTRO SEGÚN EL ITEM SELECCIONADO
        switch (itemSeleccionado) {
            case "Persona Externa":
                new PersonaExternaVista().setVisible(true);
                break;
            case "Estudiante":
                new EstudianteVista().setVisible(true);
                break;
            case "Trabajador":
                new TrabajadorVista().setVisible(true);
                break;
            case "Profesor":
                new ProfesorVista().setVisible(true);
                break;
            case "Decano":
                new DecanoVista().setVisible(true);
                break;
            default:    
                // Manejar el caso por defecto si es necesario
                break;
        }
    }//GEN-LAST:event_btnRegistrarJLabelMouseClicked

    public javax.swing.JPanel getContenidoPrincipalJPanel() {
        return contenidoPrincipalJPanel;
    }

    public void mostrarPanel(javax.swing.JPanel panel) {
        contenidoPrincipalJPanel.removeAll();
        contenidoPrincipalJPanel.add(panel);
        contenidoPrincipalJPanel.revalidate();
        contenidoPrincipalJPanel.repaint();
    }
    private void personaExternaJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaExternaJButtonMouseClicked
        // TODO add your handling code here:
        PersonaExternaPanel personaExternaPanel = new PersonaExternaPanel();
        mostrarPanel(personaExternaPanel);

    }//GEN-LAST:event_personaExternaJButtonMouseClicked

    private void trabajadoresJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajadoresJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trabajadoresJButtonMouseClicked

    private void estudiantesJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiantesJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiantesJButtonMouseClicked

    private void profesoresJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesoresJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profesoresJButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UniversidadSanWilliamJLabel;
    private javax.swing.JLabel bienvenidoAlSistemaAcademicoJLabel;
    private javax.swing.JLabel btnAcercaDeJLabel;
    private javax.swing.JLabel btnConfiguracionJLabel;
    private javax.swing.JLabel btnInicioJLabel;
    private javax.swing.JLabel btnRegistrarJLabel;
    private javax.swing.JLabel btnSalirJLabel;
    private javax.swing.JTextField buscarBarraJTextField;
    private javax.swing.JPanel contenidoDeBotonesJPanel;
    private javax.swing.JPanel contenidoPrincipalJPanel;
    private javax.swing.JButton estudiantesJButton;
    private javax.swing.JPanel fondoMenuJPanel2;
    private javax.swing.JPanel fondoPrincipalJPanel1;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JLabel imgUniversidadJLabel;
    private javax.swing.JComboBox<String> itemRolesPTEPJComboBox;
    private javax.swing.JPanel menuItemJPanel;
    private javax.swing.JButton personaExternaJButton;
    private javax.swing.JButton profesoresJButton;
    private javax.swing.JPanel toolbarJPanel;
    private javax.swing.JButton trabajadoresJButton;
    // End of variables declaration//GEN-END:variables
}
