/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistas.paneles;

import com.mycompany.controladores.DecanoControlador;
import com.mycompany.idecanos.Decano;
import com.mycompany.vistas.MainWindow;
import com.mycompany.vistas.sistema.DecanoVista;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibarr
 */
public class DecanosPanel extends javax.swing.JPanel {

    // CONTROLADOR PARA MANEJAR LA LOGICA DE DECANOS
    private DecanoControlador controlador;

    /**
     * Creates new form DecanosPanel
     */
    public DecanosPanel() {
        initComponents();
        // INICIALIZAR EL CONTROLADOR SIN VISTA
        controlador = new DecanoControlador();
        // CARGAR DATOS INICIALES EN LA TABLA
        actualizarTabla(controlador.obtenerDecanos());
    }

    // CONSTRUCTOR ALTERNATIVO QUE ACEPTA UN CONTROLADOR
    public DecanosPanel(DecanoControlador controlador) {
        initComponents();
        this.controlador = controlador;
        // CARGAR DATOS INICIALES EN LA TABLA
        actualizarTabla(controlador.obtenerDecanos());
    }

    // METODO PARA ACTUALIZAR LA TABLA CON DATOS DE DECANOS
    public void actualizarTabla(Decano[] decanos) {
        DefaultTableModel modelo = (DefaultTableModel) tablaDatosDecanosJTable.getModel();
        modelo.setRowCount(0); // LIMPIAR TABLA
        
        if (decanos != null) {
            for (Decano decano : decanos) {
                if (decano != null) {
                    Object[] fila = {
                        decano.getNombre(),
                        decano.getId(),
                        decano.getCedula(),
                        decano.getCorreoInstitucional(),
                        decano.getCorreoPersonal(),
                        decano.getSueldo(),
                        decano.getDedicacion(),
                        decano.getNivel()
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }

    // METODO PARA BUSCAR DECANOS POR NOMBRE
    public void buscarDecanosPorNombre(String nombre) {
        Decano[] decanosEncontrados = controlador.buscarDecanosPorNombre(nombre);
        actualizarTabla(decanosEncontrados);
    }

    // METODO GETTER PARA EL CONTROLADOR
    public DecanoControlador getControlador() {
        return controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMainJPanel = new javax.swing.JPanel();
        tablaJScrollPanel = new javax.swing.JScrollPane();
        tablaDatosDecanosJTable = new javax.swing.JTable();
        menuBotonesJPanel = new javax.swing.JPanel();
        btnEliminarJButton = new javax.swing.JButton();
        btnActualizarJButton = new javax.swing.JButton();

        bgMainJPanel.setBackground(new java.awt.Color(255, 255, 255));

        tablaJScrollPanel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        tablaDatosDecanosJTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tablaDatosDecanosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Cédula", "Correo Institucionall", "Correo Personal", "Sueldo", "Dedicaciòn", "Nivel"
            }
        ));
        tablaJScrollPanel.setViewportView(tablaDatosDecanosJTable);

        menuBotonesJPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarJButton.setText("Eliminar");
        btnEliminarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarJButtonMouseClicked(evt);
            }
        });

        btnActualizarJButton.setText("Actualizar");
        btnActualizarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBotonesJPanelLayout = new javax.swing.GroupLayout(menuBotonesJPanel);
        menuBotonesJPanel.setLayout(menuBotonesJPanelLayout);
        menuBotonesJPanelLayout.setHorizontalGroup(
            menuBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBotonesJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuBotonesJPanelLayout.setVerticalGroup(
            menuBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBotonesJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuBotonesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarJButton)
                    .addComponent(btnEliminarJButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout bgMainJPanelLayout = new javax.swing.GroupLayout(bgMainJPanel);
        bgMainJPanel.setLayout(bgMainJPanelLayout);
        bgMainJPanelLayout.setHorizontalGroup(
            bgMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaJScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(bgMainJPanelLayout.createSequentialGroup()
                .addComponent(menuBotonesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgMainJPanelLayout.setVerticalGroup(
            bgMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgMainJPanelLayout.createSequentialGroup()
                .addComponent(tablaJScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBotonesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgMainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgMainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarJButtonMouseClicked
        // VERIFICAR QUE SE HAYA SELECCIONADO UNA FILA
        int fila = tablaDatosDecanosJTable.getSelectedRow();

        if (fila != -1) {
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Deseas eliminar este decano?",
                "Confirmación",
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                // OBTENER ID DESDE LA COLUMNA 1 (ÍNDICE 1)
                int id = Integer.parseInt(tablaDatosDecanosJTable.getValueAt(fila, 1).toString());

                // LLAMAR AL CONTROLADOR PARA ELIMINAR
                Decano[] decanosActualizados = controlador.eliminarDecano(id);

                if (decanosActualizados != null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Decano eliminado exitosamente.");
                    actualizarTabla(decanosActualizados);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el decano.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarJButtonMouseClicked

    private void btnActualizarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarJButtonMouseClicked
        // VERIFICAR QUE SE HAYA SELECCIONADO UNA FILA
        int fila = tablaDatosDecanosJTable.getSelectedRow();

        if (fila != -1) {
            // OBTENER EL ID DESDE LA COLUMNA 1 (ÍNDICE 1)
            int id = Integer.parseInt(tablaDatosDecanosJTable.getValueAt(fila, 1).toString());

            // OBTENER EL DECANO A ACTUALIZAR
            Decano decanoAActualizar = controlador.buscarDecano(id);

            if (decanoAActualizar != null) {
                // CREAR Y MOSTRAR LA VENTANA DE ACTUALIZACIÓN
                MainWindow mainWindow = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
                DecanoVista vistaActualizacion = new DecanoVista();

                // CONFIGURAR EL MODO DE ACTUALIZACIÓN
                vistaActualizacion.configurarModoActualizacion(decanoAActualizar, fila, this);

                // MOSTRAR LA VENTANA
                vistaActualizacion.setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo obtener los datos del decano.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarJButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgMainJPanel;
    private javax.swing.JButton btnActualizarJButton;
    private javax.swing.JButton btnEliminarJButton;
    private javax.swing.JPanel menuBotonesJPanel;
    private javax.swing.JTable tablaDatosDecanosJTable;
    private javax.swing.JScrollPane tablaJScrollPanel;
    // End of variables declaration//GEN-END:variables
}
