/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistas.paneles;

/**
 *
 * @author ibarr
 */
public class DecanosPanel extends javax.swing.JPanel {

    /**
     * Creates new form DecanosPanel
     */
    public DecanosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMainJPanel12 = new javax.swing.JPanel();
        tablaJScrollPanel12 = new javax.swing.JScrollPane();
        tablaDatosPersonaExternaJTable12 = new javax.swing.JTable();
        menuBotonesJPanel12 = new javax.swing.JPanel();
        btnEliminarJButton12 = new javax.swing.JButton();
        btnActualizarJButton12 = new javax.swing.JButton();

        bgMainJPanel12.setBackground(new java.awt.Color(255, 255, 255));

        tablaJScrollPanel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        tablaDatosPersonaExternaJTable12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tablaDatosPersonaExternaJTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Cédula", "Correo Institucionall", "Correo Personal", "Sueldo", "Dedicaciòn", "Nivel"
            }
        ));
        tablaJScrollPanel12.setViewportView(tablaDatosPersonaExternaJTable12);

        menuBotonesJPanel12.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarJButton12.setText("Eliminar");
        btnEliminarJButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarJButton12MouseClicked(evt);
            }
        });

        btnActualizarJButton12.setText("Actualizar");
        btnActualizarJButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarJButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBotonesJPanel12Layout = new javax.swing.GroupLayout(menuBotonesJPanel12);
        menuBotonesJPanel12.setLayout(menuBotonesJPanel12Layout);
        menuBotonesJPanel12Layout.setHorizontalGroup(
            menuBotonesJPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBotonesJPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarJButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarJButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuBotonesJPanel12Layout.setVerticalGroup(
            menuBotonesJPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBotonesJPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuBotonesJPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarJButton12)
                    .addComponent(btnEliminarJButton12))
                .addContainerGap())
        );

        javax.swing.GroupLayout bgMainJPanel12Layout = new javax.swing.GroupLayout(bgMainJPanel12);
        bgMainJPanel12.setLayout(bgMainJPanel12Layout);
        bgMainJPanel12Layout.setHorizontalGroup(
            bgMainJPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaJScrollPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(bgMainJPanel12Layout.createSequentialGroup()
                .addComponent(menuBotonesJPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgMainJPanel12Layout.setVerticalGroup(
            bgMainJPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgMainJPanel12Layout.createSequentialGroup()
                .addComponent(tablaJScrollPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBotonesJPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgMainJPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgMainJPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarJButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarJButton12MouseClicked
        // TODO add your handling code here:
        int fila = tablaDatosPersonaExternaJTable.getSelectedRow();

        if (fila != -1) {
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Deseas eliminar esta persona?",
                "Confirmación",
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                // Obtener ID desde la columna 1 (índice 1)
                int id = Integer.parseInt(tablaDatosPersonaExternaJTable.getValueAt(fila, 1).toString());

                // Llamar al controlador
                boolean eliminado = controlador.eliminarPersonaExterna(id);

                if (eliminado) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Persona eliminada exitosamente.");
                    actualizarTabla(controlador.obtenerPersonasExternas());
                }

            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarJButton12MouseClicked

    private void btnActualizarJButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarJButton12MouseClicked
        // TODO add your handling code here:
        // VERIFICAR QUE SE HAYA SELECCIONADO UNA FILA
        int fila = tablaDatosPersonaExternaJTable.getSelectedRow();

        if (fila != -1) {
            // OBTENER EL ID DESDE LA COLUMNA 1 (ÍNDICE 1)
            int id = Integer.parseInt(tablaDatosPersonaExternaJTable.getValueAt(fila, 1).toString());

            // OBTENER LA PERSONA EXTERNA A ACTUALIZAR
            PersonaExterna personaAActualizar = controlador.obtenerPersonaExternaPorId(id);

            if (personaAActualizar != null) {
                // CREAR Y MOSTRAR LA VENTANA DE ACTUALIZACIÓN
                MainWindow mainWindow = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
                PersonaExternaVista vistaActualizacion = new PersonaExternaVista(mainWindow);

                // CONFIGURAR EL MODO DE ACTUALIZACIÓN
                vistaActualizacion.configurarModoActualizacion(personaAActualizar);

                // MOSTRAR LA VENTANA
                vistaActualizacion.setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo obtener los datos de la persona.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarJButton12MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgMainJPanel;
    private javax.swing.JPanel bgMainJPanel1;
    private javax.swing.JPanel bgMainJPanel10;
    private javax.swing.JPanel bgMainJPanel11;
    private javax.swing.JPanel bgMainJPanel12;
    private javax.swing.JPanel bgMainJPanel2;
    private javax.swing.JPanel bgMainJPanel3;
    private javax.swing.JPanel bgMainJPanel4;
    private javax.swing.JPanel bgMainJPanel5;
    private javax.swing.JPanel bgMainJPanel6;
    private javax.swing.JPanel bgMainJPanel7;
    private javax.swing.JPanel bgMainJPanel8;
    private javax.swing.JPanel bgMainJPanel9;
    private javax.swing.JButton btnActualizarJButton;
    private javax.swing.JButton btnActualizarJButton1;
    private javax.swing.JButton btnActualizarJButton10;
    private javax.swing.JButton btnActualizarJButton11;
    private javax.swing.JButton btnActualizarJButton12;
    private javax.swing.JButton btnActualizarJButton2;
    private javax.swing.JButton btnActualizarJButton3;
    private javax.swing.JButton btnActualizarJButton4;
    private javax.swing.JButton btnActualizarJButton5;
    private javax.swing.JButton btnActualizarJButton6;
    private javax.swing.JButton btnActualizarJButton7;
    private javax.swing.JButton btnActualizarJButton8;
    private javax.swing.JButton btnActualizarJButton9;
    private javax.swing.JButton btnEliminarJButton;
    private javax.swing.JButton btnEliminarJButton1;
    private javax.swing.JButton btnEliminarJButton10;
    private javax.swing.JButton btnEliminarJButton11;
    private javax.swing.JButton btnEliminarJButton12;
    private javax.swing.JButton btnEliminarJButton2;
    private javax.swing.JButton btnEliminarJButton3;
    private javax.swing.JButton btnEliminarJButton4;
    private javax.swing.JButton btnEliminarJButton5;
    private javax.swing.JButton btnEliminarJButton6;
    private javax.swing.JButton btnEliminarJButton7;
    private javax.swing.JButton btnEliminarJButton8;
    private javax.swing.JButton btnEliminarJButton9;
    private javax.swing.JPanel menuBotonesJPanel;
    private javax.swing.JPanel menuBotonesJPanel1;
    private javax.swing.JPanel menuBotonesJPanel10;
    private javax.swing.JPanel menuBotonesJPanel11;
    private javax.swing.JPanel menuBotonesJPanel12;
    private javax.swing.JPanel menuBotonesJPanel2;
    private javax.swing.JPanel menuBotonesJPanel3;
    private javax.swing.JPanel menuBotonesJPanel4;
    private javax.swing.JPanel menuBotonesJPanel5;
    private javax.swing.JPanel menuBotonesJPanel6;
    private javax.swing.JPanel menuBotonesJPanel7;
    private javax.swing.JPanel menuBotonesJPanel8;
    private javax.swing.JPanel menuBotonesJPanel9;
    private javax.swing.JTable tablaDatosPersonaExternaJTable;
    private javax.swing.JTable tablaDatosPersonaExternaJTable1;
    private javax.swing.JTable tablaDatosPersonaExternaJTable10;
    private javax.swing.JTable tablaDatosPersonaExternaJTable11;
    private javax.swing.JTable tablaDatosPersonaExternaJTable12;
    private javax.swing.JTable tablaDatosPersonaExternaJTable2;
    private javax.swing.JTable tablaDatosPersonaExternaJTable3;
    private javax.swing.JTable tablaDatosPersonaExternaJTable4;
    private javax.swing.JTable tablaDatosPersonaExternaJTable5;
    private javax.swing.JTable tablaDatosPersonaExternaJTable6;
    private javax.swing.JTable tablaDatosPersonaExternaJTable7;
    private javax.swing.JTable tablaDatosPersonaExternaJTable8;
    private javax.swing.JTable tablaDatosPersonaExternaJTable9;
    private javax.swing.JScrollPane tablaJScrollPanel;
    private javax.swing.JScrollPane tablaJScrollPanel1;
    private javax.swing.JScrollPane tablaJScrollPanel10;
    private javax.swing.JScrollPane tablaJScrollPanel11;
    private javax.swing.JScrollPane tablaJScrollPanel12;
    private javax.swing.JScrollPane tablaJScrollPanel2;
    private javax.swing.JScrollPane tablaJScrollPanel3;
    private javax.swing.JScrollPane tablaJScrollPanel4;
    private javax.swing.JScrollPane tablaJScrollPanel5;
    private javax.swing.JScrollPane tablaJScrollPanel6;
    private javax.swing.JScrollPane tablaJScrollPanel7;
    private javax.swing.JScrollPane tablaJScrollPanel8;
    private javax.swing.JScrollPane tablaJScrollPanel9;
    // End of variables declaration//GEN-END:variables
}
